arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - theta_1
    - theta_2
    - theta_3
  gains:
    theta_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    theta_2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    theta_3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1