<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="simon">
     
    <!-- This is an URDF representation of Simon's robotic arm -->


    <xacro:include filename="inertial_macros.xacro"/>
    <xacro:property name="pi" value="3.1415926535897931" />

    <material name="blue">
        <color rgba="0 0 0.8 1"/>
    </material>

    <material name="green">
        <color rgba="0 0.8 0 1"/>
    </material>

    <material name="grey">
        <color rgba="0.6 0.6 0.6 1"/>
    </material>

    <!-- World link -->
    <link name="world">
    </link>

    <!-- base_joint -->
    <joint name="base_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="world" />
        <child link="base_link" />
    </joint>


    <!-- base_link is a large rectangular plate -->
    <link name="base_link">
        <visual>
            <origin xyz="-0.2 0 0.01" rpy="0 0 0"/>
            <geometry>
                <box size="1 0.5 0.02"/>
            </geometry>
            <material name="grey" />
        </visual>
        <collision>
            <origin xyz="-0.2 0 0.01" rpy="0 0 0"/>
            <geometry>
                <box size="1 0.5 0.02"/>
            </geometry>
        </collision>
    </link>


    <!-- Fixed joint between base and link_1 -->
    <joint name="base_link_1" type="fixed">
        <origin xyz="0 0 0.02" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="link_1" />
    </joint>


    <!-- link_1 -->
    <xacro:property name="link_length" value="0.036" />
    <xacro:property name="link_radius" value="0.01" />

    <link name="link_1">
        <visual>
            <origin xyz="0 0 ${link_length/2}" rpy="0 0 0" />
            <geometry>
                <cylinder length="${link_length}" radius="${link_radius}"/>
            </geometry>
            <material name="green" />
        </visual>
        <collision>
            <origin xyz="0 0 ${link_length/2}" rpy="0 0 0" />
            <geometry>
                <cylinder length="${link_length}" radius="${link_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.3" length="${link_length}" radius="${link_radius}">
            <!-- Specifies the center of gravity and the inertial reference frame
            (relative to the link's reference frame) -->
            <origin xyz="0 0 ${link_length/2}" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>


    <!-- theta_1 allows link_1 to rotate with respect to base_link -->
    <joint name="theta_1" type="revolute">
        <origin xyz="0 0 ${link_length}" rpy="0 0 0" />
        <parent link="link_1" />
        <child link="link_2" />
        <axis xyz="0 0 1" />
        <limit lower="-${pi/2}" upper="${pi/2}" velocity="100" effort="1000.0" />
    </joint>


    <!-- link_2 -->
    <xacro:property name="link_length" value="0.05" />

    <link name="link_2">
        <visual>
            <origin xyz="${link_length/2} 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder length="${link_length}" radius="${link_radius}"/>
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <origin xyz="${link_length/2} 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder length="${link_length}" radius="${link_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.4" length="${link_length}" radius="${link_radius}">
            <origin xyz="${link_length/2} 0 0" rpy="0 ${pi/2} 0" />
        </xacro:inertial_cylinder>
    </link>


    <!-- theta_2 allows link_3 to rotate with respect to link_2 -->
    <joint name="theta_2" type="revolute">
        <origin xyz="${link_length} 0 0" rpy="0 0 0" />
        <parent link="link_2" />
        <child link="link_3" />
        <axis xyz="0 1 0" />
        <limit lower="-1" upper="${pi/2}" velocity="100" effort="100" />
    </joint>


    <!-- link_3 -->
    <xacro:property name="link_length" value="0.485" />

    <link name="link_3">
        <visual>
            <origin xyz="0 0 ${link_length/2}" rpy="0 0 0" />
            <geometry>
                <cylinder length="${link_length}" radius="${link_radius}"/>
            </geometry>
            <material name="green" />
        </visual>
        <collision>
            <origin xyz="0 0 ${link_length/2}" rpy="0 0 0" />
            <geometry>
                <cylinder length="${link_length}" radius="${link_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1" length="${link_length}" radius="${link_radius}">
            <origin xyz="0 0 ${link_length/2}" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>


    <!-- theta_3 allows link_4 to rotate with respect to link_3 -->
    <joint name="theta_3" type="revolute">
        <origin xyz="0 0 ${link_length}" rpy="0 0 0" />
        <parent link="link_3" />
        <child link="link_4" />
        <axis xyz="0 1 0" />
        <limit lower="-${pi/2}" upper="1" velocity="100" effort="1000.0" />
    </joint>


    <!-- link_4 -->
    <xacro:property name="link_length" value="0.36" />

    <link name="link_4">
        <visual>
            <origin xyz="${link_length/2} 0 0" rpy="0 ${pi/2} 0" />    
            <geometry>
                <cylinder length="${link_length}" radius="${link_radius}"/>
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <origin xyz="${link_length/2} 0 0" rpy="0 ${pi/2} 0" />    
            <geometry>
                <cylinder length="${link_length}" radius="${link_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.75" length="${link_length}" radius="${link_radius}">
            <origin xyz="${link_length/2} 0 0" rpy="0 ${pi/2} 0" />
        </xacro:inertial_cylinder>
    </link>


    <!-- theta_4 allows link_5 to rotate with respect to link_4 -->
    <joint name="theta_4" type="continuous">
        <origin xyz="${link_length} 0 0" rpy="0 0 0" />
        <parent link="link_4" />
        <child link="link_5" />
        <axis xyz="1 0 0" />
    </joint>


    <!-- link_5 -->
    <xacro:property name="link_length" value="0.08" />

    <link name="link_5">
        <visual>
            <origin xyz="${link_length/2} 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder length="${link_length}" radius="${link_radius}"/>
            </geometry>
            <material name="green" />
        </visual>
        <collision>
            <origin xyz="${link_length/2} 0 0" rpy="0 ${pi/2} 0" />
            <geometry>
                <cylinder length="${link_length}" radius="${link_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.4" length="${link_length}" radius="${link_radius}">
            <origin xyz="${link_length/2} 0 0" rpy="0 ${pi/2} 0" />
        </xacro:inertial_cylinder>
    </link>


    <!-- joint at the tip of the end effector -->
    <joint name="eef_fixed" type="fixed">
        <origin xyz="${link_length} 0 0" rpy="0 0 0" />
        <parent link="link_5" />
        <child link="eef_link"/>
        
    </joint>


    <!-- link to make eef_fixed work -->
    <link name="eef_link">
    </link>
    
</robot>